
###

###

GET http://localhost:3000/api/store/get-secret/my-addresss
Accept: application/json
Content-Type: application/json

#######################################

POST http://localhost:3000/api/store/put-secret/
Accept: application/json
Content-Type: application/json

{
    "baseAddress": "my-address",
    "basePrivate": "my-private",
    "pendingAddress": "my-pending-address",
    "pendingPrivate": "my-pending-private"
}

###

GET http://localhost:3000/api/wallet/balance/GBSALEPFZQMIAOMLIBKMRGIA2OM4TE265PT2W6BZO6ASFXJGBRI2QKNJ
Accept: application/json
Content-Type: application/json

#######################################

GET http://localhost:3000/api/stellar/test?hello[]=world&hello[]=artist
Accept: application/json
Content-Type: application/json


#######################################

POST http://localhost:3000/api/stellar/wallet/create/
Accept: application/json
Content-Type: application/json

#######################################