###

GET http://localhost:3000/api/wallet/balance/RS_MAIN?assets[]=DIMO&assets[]=TNZS&include_pending=true
Accept: application/json
Content-Type: application/json

###

GET http://localhost:3000/api/wallet/balance/RS_MAIN?assets[]=DIMO&include_pending=false
Accept: application/json
Content-Type: application/json

###
POST http://localhost:3000/api/wallet/create
Accept: application/json
Content-Type: application/json

{
    "assets": "[\"BTC\", \"TNZS\"]",
    "is_user": true
}

###

###
POST http://localhost:3000/api/wallet/trust
Accept: application/json
Content-Type: application/json

{
    "assets": "[\"DIMO\"]",
    "from_acc": "GDE645YPGQHXEJOGSRQ5HF7Z2CZYFW5Q3RSOUFUVJXUYR6GFSA4EWFUJ",
    "is_user": false
}

###

POST http://localhost:3000/api/wallet/transfer
Accept: application/json
Content-Type: application/json

{
    "sender_acc": "GALOCWKVIZGOVJI67VXHL2SZSH64GHFNYGLOOI3KBFAAPVDCGNGRPOTK",
    "receiver_acc": "RS_MAIN",
    "profit_acc": "GALOCWKVIZGOVJI67VXHL2SZSH64GHFNYGLOOI3KBFAAPVDCGNGRPOTK",
    "amount": 1,
    "fee": 0,
    "asset": "DIMO"
}

###

POST http://localhost:3000/api/wallet/deposit
Accept: application/json
Content-Type: application/json

{
    "user_acc": "GB3Y27EUGF3SU3PQHSQNBHX4RYQYDHV4R3KH6XIRKDREAG6VQADHD4MP",
    "service_acc": "GB4MQVYUH2OLYSNFTTZSI2HY3J7IUW7ADWAROZC5ZWB5WKIAIEOZ57IY",
    "profit_acc": "",
    "amount": 100,
    "fee": 10,
    "asset": "DIMO"
}

###

POST http://localhost:3000/api/wallet/hold/GDCOAHYVR4FVC4F2Y2CWN33QAKAGCH7OSNQ27KESJ7QMXQSPZDRGQJFX
Accept: application/json
Content-Type: application/json

{
    "amount": 2,
    "asset": "DIMO",
    "reverse": false
}

###

POST http://localhost:3000/api/wallet/withdraw
Accept: application/json
Content-Type: application/json

{
    "user_acc": "",
    "service_acc": "",
    "profit_acc": "",
    "amount": 2,
    "fee": 1,
    "asset": "DIMO"
}

###

POST http://localhost:3000/api/wallet/exchange
Accept: application/json
Content-Type: application/json

{
    "from_acc": "",
    "to_acc": "",
    "profit_acc": "",
    "amount_from": 2,
    "amount_to": 2,
    "fee": 1,
    "asset_from": "DIMO",
    "asset_to": "TNZS"
}

###

POST http://localhost:3000/api/wallet/create-asset/
Accept: application/json
Content-Type: application/json

{
    "asset_name": "ARTIST",
    "amount": 23
}

###
