###

GET http://localhost:3000/api/wallet/balance/GB225PSJUIBHSA5C2CIAO55LPVEQZRV42F57ONRFDSYEXZTUD56WPG6R?assets[]=DIMO
Accept: application/json
Content-Type: application/json

###

POST http://localhost:3000/api/wallet/create
Accept: application/json
Content-Type: application/json

{
    "assets": "[\"DIMO\", \"ADD\"]",
    "is_user": true
}

###

POST http://localhost:3000/api/wallet/transfer
Accept: application/json
Content-Type: application/json

{
    "sender_acc": "GA5TB27YTNL6VELOIF5H2RRT5NG2L5NCMNO6XW4KCF53NTQ6YIBZQT34",
    "receiver_acc": "GA7ZRG6YCNCOYRTWDVWC62JE2C7TAFLFXPZVC7GE735OIN6JG364WSMQ",
    "profit_acc": "GB225PSJUIBHSA5C2CIAO55LPVEQZRV42F57ONRFDSYEXZTUD56WPG6R",
    "amount": 100,
    "fee": 18,
    "asset": "DIMO"
}

###
